Doing it right! Building tagged docker img!
Thanks A LOT to Thomas Juerges for the excellent help in this

diff --git a/docker/mk_image_and_push b/docker/mk_image_and_push
--- a/docker/mk_image_and_push
+++ b/docker/mk_image_and_push
@@ -1,2 +1,11 @@
-sudo docker build -t haavee/jiveplot .
-sudo docker push haavee/jiveplot
+#!/bin/bash
+VERSION=latest
+if [ -n "$1" ]; then
+    VERSION=$1
+fi
+sudo docker build --build-arg JIVEPLOT_VERSION=${VERSION} -t haavee/jiveplot:${VERSION} .
+if [ $? -eq 0 ]; then
+    sudo docker push haavee/jiveplot:${VERSION}
+else
+    echo "You're doing it wrong - #FAIL to build version ${VERSION}"
+fi
